package age

import (
	"fmt"
	"github.com/1Password/shell-plugins/sdk"
	"github.com/1Password/shell-plugins/sdk/importer"
	"github.com/1Password/shell-plugins/sdk/schema"
	"github.com/1Password/shell-plugins/sdk/schema/credname"
	"github.com/1Password/shell-plugins/sdk/schema/fieldname"
)

func Recipients() schema.CredentialType {
	return schema.CredentialType{
		Name:          credname.Recipients,
		DocsURL:       sdk.URL("https://age.com/docs/secret_key"),              // TODO: Replace with actual URL
		ManagementURL: sdk.URL("https://console.age.com/user/security/tokens"), // TODO: Replace with actual URL
		Fields: []schema.CredentialField{
			{
				Name:                fieldname.Recipients,
				MarkdownDescription: "List of age public keys to use as recipients for encryption.",
				Secret:              true, // not actually a secret but required to pass validation
				Composition: &schema.ValueComposition{
					Charset: schema.Charset{
						Lowercase: true,
						Digits:    true,
					},
				},
			},
		},
		DefaultProvisioner: TempRecipientsFile(materialiseRecipientsFile),
		Importer:           importer.NoOp(),
	}
}

func materialiseRecipientsFile(in sdk.ProvisionInput) ([]byte, error) { // Get the current time
	content := "# generated by: 1password-cli/shell-plugins/plugin/age\n"

	if recipients, ok := in.ItemFields[fieldname.Recipients]; ok {
		content += fmt.Sprintf(recipients)
	}

	return []byte(content), nil
}
