package age

import (
	"github.com/1Password/shell-plugins/plugins/age/provisioner"
	"github.com/1Password/shell-plugins/sdk"
	"github.com/1Password/shell-plugins/sdk/importer"
	"github.com/1Password/shell-plugins/sdk/schema"
	"github.com/1Password/shell-plugins/sdk/schema/credname"
	"github.com/1Password/shell-plugins/sdk/schema/fieldname"
)

func Recipients() schema.CredentialType {
	return schema.CredentialType{
		Name:    credname.SecretKey,
		DocsURL: sdk.URL("https://age-encryption.org/"),
		Fields: []schema.CredentialField{
			{
				Name:                fieldname.PublicKey,
				MarkdownDescription: "Age X25519 public key.",
				Secret:              false,
				Composition: &schema.ValueComposition{
					Length: 62,
					Charset: schema.Charset{
						Lowercase: true,
						Digits:    true,
					},
				},
			},
		},
		DefaultProvisioner: provisioner.RecipientsTempFile(materialiseRecipientsFile),
		Importer:           importer.NoOp(),
	}
}

func materialiseRecipientsFile(in sdk.ProvisionInput) ([]byte, error) {
	content := "# generated by: 1password-cli/shell-plugins/plugin/age\n"

	if publicKey, ok := in.ItemFields[fieldname.PublicKey]; ok {
		content += publicKey
	}

	return []byte(content), nil
}
